### PR TITLE
Added method to get inputs using only uuids

### PR DESCRIPTION
**Pull request by Ragge-dev**
Solves: https://annotell.atlassian.net/browse/INT-406

### CODE REVIEW

**Review by cotramarko — COMMENTED** [review]
Nice!

However, shouldn't this also be added to `annoutil`?

**Comment by Ragge-dev** [comment]
> Nice!
> 
> However, shouldn't this also be added to `annoutil`?

Added it to annoutil.
I am all for removing that though, in favor of doing something in the app.

**Comment by fredrikjacobson** [comment]
> > Nice!
> > However, shouldn't this also be added to `annoutil`?
> 
> Added it to annoutil.
> I am all for removing that though, in favor of doing something in the app.

What does doing something in the app mean?

**Comment by Ragge-dev** [comment]
> > > Nice!
> > > However, shouldn't this also be added to `annoutil`?
> > 
> > 
> > Added it to annoutil.
> > I am all for removing that though, in favor of doing something in the app.
> 
> What does doing something in the app mean?

I was refering to our discussion of removing annoutil alltogether, it has nothing to do with this PR it was just on the top of my mind... Lets take that outside of this PR.

**Pull request merged**
