### PR TITLE
use backport of datatables to support python 3.6

### PR DESCRIPTION
**Pull request by MichelEdkrantz**
- use backport of datatables to support python 3.6
- fix some more dependencies

### CODE REVIEW

**Comment by fredrikjacobson** [comment]
Vi använder tyvärr PIL för att vi måste lista ut bildstorlek.. 
`from PIL import Image`

**Review by TheoBerglin — APPROVED** [review]
Great! 🍻

**Comment by MichelEdkrantz** [comment]
Ok, great. Feel free to reintegrate this whenever is a good time then.

**Comment by fredrikjacobson** [comment]
https://github.com/annotell/annotell-python/pull/34

backporting will be performed in the above PR, closing this one

**Pull request closed without merging**
